

CREATE TABLE public.cart_items (
                                   id bigint NOT NULL,
                                   added_at timestamp(6) without time zone NOT NULL,
                                   quantity integer NOT NULL,
                                   cart_id bigint NOT NULL,
                                   product_id bigint NOT NULL
);



ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.carts (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              updated_at timestamp(6) without time zone NOT NULL,
                              user_id bigint NOT NULL
);



ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.categories (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) without time zone NOT NULL,
                                   description character varying(500),
                                   image_url character varying(255),
                                   name character varying(100) NOT NULL
);



ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.external_recommendations (
                                                 id bigint NOT NULL,
                                                 created_at timestamp(6) without time zone NOT NULL,
                                                 expires_at timestamp(6) without time zone NOT NULL,
                                                 platform character varying(50) NOT NULL,
                                                 recommendations_json text NOT NULL,
                                                 search_query character varying(500) NOT NULL
);



ALTER TABLE public.external_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.external_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.notifications (
                                      id bigint NOT NULL,
                                      action_url character varying(255),
                                      created_at timestamp(6) without time zone NOT NULL,
                                      is_read boolean NOT NULL,
                                      message text NOT NULL,
                                      title character varying(200) NOT NULL,
                                      type character varying(30) NOT NULL,
                                      user_id bigint NOT NULL,
                                      CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['ORDER_CONFIRMED'::character varying, 'ORDER_SHIPPED'::character varying, 'ORDER_DELIVERED'::character varying, 'STOCK_ALERT'::character varying, 'PRICE_DROP'::character varying, 'PROMOTION'::character varying, 'ACCOUNT'::character varying])::text[])))
);



ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.order_items (
                                    id bigint NOT NULL,
                                    price_at_purchase numeric(10,2) NOT NULL,
                                    quantity integer NOT NULL,
                                    order_id bigint NOT NULL,
                                    product_id bigint NOT NULL
);



ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.orders (
                               id bigint NOT NULL,
                               created_at timestamp(6) without time zone NOT NULL,
                               notes character varying(1000),
                               order_number character varying(50) NOT NULL,
                               payment_method character varying(50) NOT NULL,
                               shipping_address character varying(500) NOT NULL,
                               shipping_city character varying(100) NOT NULL,
                               shipping_country character varying(100),
                               shipping_postal_code character varying(20) NOT NULL,
                               status character varying(20) NOT NULL,
                               total_price numeric(10,2) NOT NULL,
                               updated_at timestamp(6) without time zone NOT NULL,
                               user_id bigint NOT NULL,
                               CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);



ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.products (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 description text,
                                 image_url character varying(255),
                                 is_active boolean NOT NULL,
                                 name character varying(200) NOT NULL,
                                 price numeric(10,2) NOT NULL,
                                 stock integer NOT NULL,
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 category_id bigint NOT NULL,
                                 supplier_id bigint NOT NULL
);



ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.suppliers (
                                  id bigint NOT NULL,
                                  address character varying(500),
                                  contact_email character varying(100) NOT NULL,
                                  contact_phone character varying(20),
                                  created_at timestamp(6) without time zone NOT NULL,
                                  name character varying(100) NOT NULL,
                                  website character varying(255)
);



ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.users (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              email character varying(100) NOT NULL,
                              email_confirmation_token character varying(255),
                              first_name character varying(50) NOT NULL,
                              is_email_confirmed boolean NOT NULL,
                              last_name character varying(50) NOT NULL,
                              password character varying(255) NOT NULL,
                              phone_number character varying(20),
                              role character varying(20) NOT NULL,
                              updated_at timestamp(6) without time zone NOT NULL,
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.wishlists (
                                  id bigint NOT NULL,
                                  added_at timestamp(6) without time zone NOT NULL,
                                  product_id bigint NOT NULL,
                                  user_id bigint NOT NULL
);



ALTER TABLE public.wishlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.external_recommendations
    ADD CONSTRAINT external_recommendations_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);



ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT uk6kn9kjr08kvm2hf0xndhcxyy6 UNIQUE (contact_email);



ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT ukht6e6158srxsvjciahp1kjywf UNIQUE (user_id, product_id);



ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);



ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);



ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fk330pyw2el06fn5g28ypyljt16 FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6i174ixi9087gcvvut45em7fd FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);



ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);



ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fkl7ao98u2bm8nijc1rv4jobcrx FOREIGN KEY (product_id) REFERENCES public.products(id);



ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);



ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);



ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);
