CREATE TABLE public.feedbacks (
                                  id              bigint NOT NULL,
                                  user_id         bigint NOT NULL,
                                  category        character varying(100) NOT NULL,
                                  experience      character varying(50)  NOT NULL,
                                  useful_features character varying(500),
                                  suggestions     text,
                                  created_at      timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fk_feedbacks_user FOREIGN KEY (user_id) REFERENCES public.users(id);