package com.ecommerce.ecommerceapp.service

import com.ecommerce.ecommerceapp.dto.auth.AuthResponse
import com.ecommerce.ecommerceapp.dto.auth.LoginRequest
import com.ecommerce.ecommerceapp.dto.auth.RegisterRequest
import com.ecommerce.ecommerceapp.entity.User
import com.ecommerce.ecommerceapp.enums.Role
import com.ecommerce.ecommerceapp.repository.UserRepository
import com.ecommerce.ecommerceapp.security.JwtTokenProvider
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.stereotype.Service
import java.time.LocalDateTime

@Service
class AuthService(
    private val userRepository: UserRepository,
    private val passwordEncoder: PasswordEncoder,       // Injected from SecurityConfig @Bean
    private val jwtTokenProvider: JwtTokenProvider
) {

    // REGISTER - Create a new user account
    fun register(request: RegisterRequest): AuthResponse {
        // Step 1: Check if email is already taken
        if (userRepository.existsByEmail(request.email)) {
            throw IllegalArgumentException("Email '${request.email}' is already in use")
        }

        // Step 2: Hash the password BEFORE saving to database
        val hashedPassword = passwordEncoder.encode(request.password)
            ?: throw IllegalArgumentException("Password encoding failed")
        // ↑ ?: throw = dacă encode returnează null (n-ar trebui), aruncăm eroare

        // Step 3: Create the User entity
        val user = User(
            id = null,                                          // ← ADĂUGAT: generated by DB
            firstName = request.firstName,
            lastName = request.lastName,
            email = request.email,
            password = hashedPassword,                          // ← Acum e garantat non-null
            phoneNumber = null,                                 // ← ADĂUGAT: not provided at register
            role = Role.USER,
            isEmailConfirmed = true,
            emailConfirmationToken = null,                      // ← ADĂUGAT: not used for now
            createdAt = LocalDateTime.now(),
            updatedAt = LocalDateTime.now()
        )

        // Step 4: Save user to database
        val savedUser = userRepository.save(user)

        // Step 5: Generate JWT token for the new user
        val token = jwtTokenProvider.generateToken(savedUser)

        // Step 6: Return token + user info to frontend
        return AuthResponse(
            token = token,
            email = savedUser.email,
            role = savedUser.role.name
        )
    }

    // LOGIN - Authenticate an existing user
    fun login(request: LoginRequest): AuthResponse {
        // Step 1: Find user by email
        val user = userRepository.findByEmail(request.email)
            .orElseThrow { IllegalArgumentException("Invalid email or password") }
        // NOTE: We say "Invalid email or password" (not "Email not found")
        // This is a security best practice - don't reveal WHICH field is wrong!

        // Step 2: Compare entered password with stored hash
        // bcrypt.matches("parola123", "$2a$10$xBnRFm...") → true/false
        if (!passwordEncoder.matches(request.password, user.password)) {
            throw IllegalArgumentException("Invalid email or password")
        }

        // Step 3: Generate a NEW token (refreshes expiration time)
        val token = jwtTokenProvider.generateToken(user)

        // Step 4: Return token + user info
        return AuthResponse(
            token = token,
            email = user.email,
            role = user.role.name
        )
    }
}